logging:
  level:
    blog: WARN
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor: ERROR
      nodeValue: WARN
      springframework:
        security: ERROR
server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://home_manager_user:iy9B11DQsbUJPVuvejvA4V0AjaFOFWkM@dpg-cftgi99a6gdotceoiqd0-a.frankfurt-postgres.render.com/home_manager
    username: home_manager_user
    password: ${db_password}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.abv.bg
    protocol: smtp
    jndi-name: mail/Session
    username: homgr@abv.bg
    password: ${mail_password}
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          mime:
            charset: true
  mvc:
    hidden-method:
      filter:
        enabled: true
  sql:
    init:
      mode: never
  thymeleaf:
    cache: false
    enabled: true
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/