# INSERT INTO home_manager.users (id, email, name, password, registered_on, reset_password_token) VALUES (1, 'b_davidov@abv.bg', 'Борис Илиев', '2a01a8413059b8075ffde4c2ad3ea0a3abd7c6911fd3d98b9344370e56c9ad784cea17d3f4fa4e4b', '2022-11-28 18:09:43.943933', null);
# INSERT INTO home_manager.users (id, email, name, password, registered_on, reset_password_token) VALUES (2, 'd_borislavova@abv.bg', 'Десислава Николова', 'b166a4d96fd2445c44f8fb90c3c3b86e3320b383eab4c568d5de625cc003a93031ca1f00b01cabdc', '2022-12-17 20:01:42.142295', null);
#
# INSERT INTO home_manager.user_roles (user_id, role_id) VALUE (1, 1);
# INSERT INTO home_manager.user_roles (user_id, role_id) VALUE (1, 2);
# INSERT INTO home_manager.user_roles (user_id, role_id) VALUE (1, 3);
#
# INSERT INTO home_manager.user_roles (user_id, role_id) VALUE (2, 2);
# INSERT INTO home_manager.user_roles (user_id, role_id) VALUE (2, 3);
#
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (1, '1', '1', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (2, '1', '2', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (3, '2', '3', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (4, '2', '4', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (5, '2', '5', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (6, '3', '6', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (7, '3', '7', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (8, '3', '8', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (9, '4', '9', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (10, '4', '10', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (11, '4', '11', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (12, '5', '12', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (13, '5', '13', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (14, '5', '14', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (15, '6', '15', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (16, '6', '16', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (17, '6', '17', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (18, '7', '18', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (19, '7', '19', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (20, '7', '20', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (21, '8', '21', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (22, '8', '22', 0.00, 1, null);
# INSERT INTO home_manager.homes (id, floor, name, total_for_month, homes_group_id, owner_id) VALUES (23, '8', '23', 0.00, 1, null);
#
#
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (1, '', 'Милен', '', '', '', 1);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (2, '', 'Кирил', 'Николов', '', '', 2);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (3, '', 'Веска', 'Берова', '', '', 3);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (4, '', 'Анелия', 'Димитрова', '', '', 4);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (5, '', 'Гергана', 'Серванова', '', '', 5);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (6, 'b_davidov@abv.bg', 'Борис', 'Илиев', 'Давидов', '0883325632', 6);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (7, '', 'Момчил', '', '', '', 7);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (8, '', 'Димитрина', 'Дурева', '', '', 8);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (9, '', 'Георги', 'Бекяров', '', '', 9);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (10, '', 'Силвия', 'Ангелова', '', '', 10);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (11, '', 'Седефка', 'Пенкова', '', '', 11);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (12, '', 'Лидия', 'Янева', '', '', 12);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (13, '', 'Георгиеви', '', '', '', 13);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (14, '', 'Николай', 'Николов', '', '', 14);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (15, '', 'Пламен', 'Арсов', '', '', 15);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (16, '', 'Иван', 'Христов', '', '', 16);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (17, '', 'Силвия', 'Николова', '', '', 17);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (18, '', 'Цона', 'Иванова', '', '', 18);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (19, '', 'Мая', 'Петрова', '', '0888456129', 19);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (20, '', 'Георги', '', '', '', 20);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (21, '', 'Красимира', 'Костадинова', '', '', 21);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (22, '', 'Нямам даннни', '', '', '', 22);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (23, '', 'Димитрина', 'Демирева', '', '', 23);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (24, '', 'Ивето', '', '', '0882837233', 1);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (25, '', 'Рая', '', '', '', 1);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (26, '', 'Бабата', '', '', '', 3);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (27, '', 'Дете 1', '', '', '', 4);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (28, '', 'Дете 2', '', '', '', 4);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (29, '', 'Пламен', '', '', '', 5);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (30, 'd_borislavova@abv.bg', 'Десислава', 'Николова', 'Бориславова', '0883301914', 6);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (31, '', 'Биляна', 'Давидова', 'Борисова', '', 6);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (32, '', 'Жена му', '', '', '', 7);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (33, '', 'Мъжът ѝ', '', '', '', 8);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (34, '', 'Ивета', '', '', '', 11);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (35, '', 'Мони', '', '', '', 11);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (36, '', 'Жената', '', '', '', 13);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (37, '', 'Жена му', '', '', '', 15);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (38, '', 'Амбра', '', '', '', 15);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (39, '', 'Брат ѝ', '', '', '', 15);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (40, '', 'Мъжът ѝ', '', '', '', 17);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (41, '', 'Дете', '', '', '', 17);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (42, '', 'Жена му', '', '', '', 20);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (43, '', 'Дете 1', '', '', '', 20);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (44, '', 'Дете 2', '', '', '', 20);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (45, '', 'Бончо', '', '', '', 21);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (46, '', 'Мъж', '', '', '', 23);
# INSERT INTO home_manager.residents (id, email, first_name, last_name, middle_name, phone_number, home_id) VALUES (47, '', 'Дете', '', '', '', 23);
